# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
      kernelModules = [];
    };
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpfs";
      options = ["defaults" "size=2G" "mode=755"];
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/1C12-2DE6";
      fsType = "vfat";
    };
    "/home" = {
      device = "/dev/disk/by-uuid/45b5f20e-b959-4dce-b423-901b0f9992ad";
      fsType = "btrfs";
      options = ["subvol=@home" "compress-force=zstd:15" "defaults" "noatime"];
    };
    "/nix" = {
      device = "/dev/disk/by-uuid/45b5f20e-b959-4dce-b423-901b0f9992ad";
      fsType = "btrfs";
      options = ["subvol=@nix" "compress-force=zstd:15" "defaults" "noatime"];
    };
    "/srv/Media" = {
      device = "/dev/disk/by-uuid/23fc1491-b1f6-4e69-82e7-6135e4c0a3f1";
      fsType = "btrfs";
      options = ["compress-force=zstd:15" "defaults" "noatime" "autodefrag" "nofail"];
    };
    "/srv" = {
      device = "/dev/disk/by-uuid/c5dde26d-1377-4ec4-8e25-707f3ef31ed7";
      fsType = "btrfs";
      options = ["subvol=@data" "compress-force=zstd:15" "defaults" "noatime"];
    };
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
